#!/bin/bash
set -ex
(cd pdns && git clean -fdx)
rsync -ravH --delete pkg-pdns/debian/ pdns/debian/
cd pdns

# no git-buildpackage here
rm -f debian/gbp.conf

# fake native package
echo '3.0 (native)' > debian/source/format

# reset GIT_COMMIT to the pdns.git commit id
export GIT_COMMIT=$(git show --pretty=oneline -s | awk '{print $1}')

# make a version using the upstream scripts
eval $(build-scripts/make-jenkins-version)
build-scripts/set-version-auth $SOURCE_VERSION $DEB_VERSION $RPM_VERSION
build-scripts/set-version-recursor $SOURCE_VERSION $DEB_VERSION $RPM_VERSION

# fix our changelog
cat >debian/changelog <<EOT
pdns ($DEB_VERSION) autotest; urgency=medium

  * Automated build based on git commit $GIT_COMMIT.

 -- Namespace Autobuild <inhuman@namespace.at>  $(date --rfc-2822)
EOT

# go build sources
(cd .. && dpkg-source -i -I -b pdns)

